<Project>
    <PropertyGroup>
        <!-- The name of the mod -->
        <NWName>NeonNetwork</NWName>
        <NWAuthor>stxticOVFL</NWAuthor>
        <!-- NWVersion is set below -->

        <!-- The name of the *DLL* -->
        <AssemblyName>$(NWName)</AssemblyName>

        <!-- Root namespace of the mod -->
        <RootNamespace>$(AssemblyName)</RootNamespace>

        <!-- The folder to copy the DLL to, e.g. Mods or Plugins -->
        <NWOutput Condition="'$(NWOutput)' == ''">
            Mods
        </NWOutput>
        <!-- Whether or not to add NeonLite as a reference. Either true or false. Looks in NWDir/Mods -->
        <NWNeonLite Condition="'$(NWNeonLite)' == ''">
            true
        </NWNeonLite>
        <!-- Whether or not to add UniverseLib as a reference. Either true or false.
             Looks in NWDir/Mods and NWDir/UserLibs -->
        <NWUniLib Condition="'$(NWUniLib)' == ''">
            true
        </NWUniLib>

        <!-- Whether or not to fill in the assembly info for you. This should usually be true.
             This also controls GenerateAssemblyInfo -->
        <NWAssembly Condition="'$(NWAssembly)' == ''">
            true
        </NWAssembly>
        <!-- The name of the class that inherits the relevant Melon class, relative to the root namespace.
             Usually this matches the name of the root namespace.
             Only used if NWAssembly is on -->
        <NWMelonClass>$(RootNamespace)</NWMelonClass>
        <!-- The color to show in the log for the project. #RRGGBB.
             Only used if NWAssembly is on -->
        <NWColor>#ABFFF8</NWColor>
        <!-- The author color to show in the log. #RRGGBB.
             Only used if NWAssembly is on -->
        <NWAuthorColor>#E17386</NWAuthorColor>

        <!-- A path to Unity scripts to additionally compile. Useful for mods with independent UIs.
             Editor scripts are skipped.
             Leave empty if no Unity scripts. Advanced users only! -->
        <NWUnityScripts>
            UnityProject/Assets/Scripts/
        </NWUnityScripts>
    </PropertyGroup>

    <Import Project=".NWCommon/NWCommon.targets" />

    <!-- Non-NWCommon properties, items, etc go here -->
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>12.0</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <!-- Add further references by using $(NWManaged) and $(NWDirectory): -->
        <Reference Include="$(NWManaged)/Unity.TextMeshPro.dll" Private="false" />
        <Reference Include="$(NWManaged)/UnityEngine.AnimationModule.dll" Private="false" />
        <Reference Include="$(NWManaged)/UnityEngine.AssetBundleModule.dll" Private="false" />
        <Reference Include="$(NWManaged)/UnityEngine.AudioModule.dll" Private="false" />
        <Reference Include="$(NWManaged)/UnityEngine.UnityWebRequestModule.dll" Private="false" />
        <Reference Include="$(NWManaged)/UnityEngine.IMGUIModule.dll" Private="false" />
        <Reference Include="$(NWManaged)/UnityEngine.UI.dll" Private="false" />
        <Reference Include="$(NWManaged)/UnityEngine.UIModule.dll" Private="false" />
        <Reference Include="$(NWDirectory)/Mods/SecretShop.dll" Private="false" />

        <None Include=".editorconfig" />
        <None Include="Resources\neonnetwork" />
        <None Include="Resources\pubkey" />
    </ItemGroup>

    <Target Name="RWVersion" BeforeTargets="GenerateNWAssembly">
        <ReadLinesFromFile Condition="Exists('version.txt')"
            File="version.txt" >
            <Output
                TaskParameter="Lines"
                ItemName="VersionLines"/>
        </ReadLinesFromFile>

        <PropertyGroup>
            <TodayComp>$([System.DateTime]::UtcNow.ToString('yyyyMMdd'))</TodayComp>
        </PropertyGroup>

        <PropertyGroup Condition="'@(VersionLines)' != ''">
            <VersionLinesP>@(VersionLines)</VersionLinesP>
            <VersionTxtDT>$(VersionLinesP.Split(';')[0])</VersionTxtDT>
            <VersionTxtBI>$(VersionLinesP.Split(';')[1])</VersionTxtBI>
        </PropertyGroup>

        <PropertyGroup Condition="'@(VersionLines)' == ''">
            <VersionTxtDT>$(TodayComp)</VersionTxtDT>
            <VersionTxtBI>0</VersionTxtBI>
        </PropertyGroup>

        <PropertyGroup Condition="'$(TodayComp)' != '$(VersionTxtDT)'">
            <VersionTxtDT>$(TodayComp)</VersionTxtDT>
            <VersionTxtBI>0</VersionTxtBI>
        </PropertyGroup>

        <PropertyGroup>
            <VersionTxtBI>$([MSBuild]::Add($(VersionTxtBI), 1))</VersionTxtBI>

            <BuildDate>$([System.DateTime]::UtcNow.ToString('yyyy.MM.dd'))</BuildDate>
            <NWVersion>$(BuildDate)+$(VersionTxtBI)</NWVersion>
            <Version>$(NWVersion.Replace('+', '.'))</Version>
        </PropertyGroup>

        <ItemGroup>
            <VersionTxtOut Include="$(VersionTxtDT)" />
            <VersionTxtOut Include="$(VersionTxtBI)" />
        </ItemGroup>

        <WriteLinesToFile
            File="version.txt"
            Lines="@(VersionTxtOut)"
            Overwrite="true"
            Encoding="Unicode" />
    </Target>

    <Target Name="PrintVersion" BeforeTargets="BeforeBuild">
      <Message Text="Version: $(NWVersion)" Importance="high" />
    </Target>


    <Import Sdk="Microsoft.NET.Sdk" Project="Sdk.targets" />
</Project>
